normalize: null

encoder: whisper
encoder_conf:
    whisper_model: small
    dropout_rate: 0.0
    use_specaug: true
    specaug_conf:
        apply_time_warp: true
        time_warp_window: 5
        time_warp_mode: bicubic
        apply_freq_mask: true
        freq_mask_width_range:
        - 0
        - 30
        num_freq_mask: 2
        apply_time_mask: true
        time_mask_width_range:
        - 0
        - 40
        num_time_mask: 2
    do_pad_trim: true         # should be set when doing zero-shot inference

decoder: whisper
decoder_conf:
    whisper_model: small
    dropout_rate: 0.0

model_conf:
    ctc_weight: 0.0
    # lsm_weight: 0.1
    length_normalized_loss: false
    sym_sos: "<|startoftranscript|>"
    sym_eos: "<|endoftext|>"
    # do_pad_trim: true         # should be set when doing zero-shot inference

frontend: null
input_size: 1                   # to prevent build_model() from complaining

seed: 2023
log_interval: 100
num_att_plot: 0
num_workers: 4
sort_in_batch: descending       # how to sort data in making batch
sort_batch: descending          # how to sort created batches
# batch_bins: 12000000            # good for single GPU w/ 40G mem
batch_type: sorted
batch_size: 5
# batch_type: numel
# batch_bins: 7000000   
# accum_grad: 4
max_epoch: 1
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 3

# use_amp: true
cudnn_deterministic: false
cudnn_benchmark: false

optim: adamw
# grad_clip: 1.0
optim_conf:
    lr: 0.0
# scheduler: warmuplr
# scheduler_conf:
#     warmup_steps: 500
